services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./genetic_tests:/genetic_tests
    
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASSWORD=pass
      
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=dbname