# Generated by Django 5.1.4 on 2024-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='animal_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='health_status',
            field=models.CharField(choices=[('good', 'Good'), ('poor', 'Poor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='species',
            field=models.CharField(max_length=255),
        ),
    ]
